# Site
name: 'bit by bit'
description: 'Bit by bit is a blog on computer engineering and many other things'
logo: 'assets/images/logo.png'
favicon: 
baseurl: ''
disqus: 
email: 'kstar1996@gmail.com'
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Eujin Kim
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Eujin"
      email:          kstar1996@gmail.com
      twitter:        

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
